name: Deploy

# Trigger the workflow on push and pull request events on the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      
      # Install PHP and dependencies
      - name: Set up PHP with dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Specify the PHP version you're using
          extensions: mbstring, pdo, tokenizer
          tools: composer
      
      # Install project dependencies
      - name: Install Dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --ignore-platform-req=ext-grpc
      
      # Run PHPStan analysis
      - name: Run PHPStan
        run: |
          vendor/bin/phpstan analyse app config database routes/api.php
      
      # Deploy to server
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /var/www/html/Necessi && ./deploy.sh"
